# Generated by Django 2.0.7 on 2018-12-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20181227_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_index', '可以查看kingadmin里多少每张表'), ('crm_table_list', '可以查看kingadmin里每张表里的数据'), ('crm_table_objs_change', '可以修改 kingadmin里每张表的数据'), ('crm_table_obj_add', '可以在 kingadmin 里的表增加数据'), ('crm_table_delete', '可以删除kingadmin中表的数据'), ('crm_table_objs_change_view', '可以修改 kingadmin里每张表的数据'), ('crm_table_obj_add_view', '可以在 kingadmin 里的表增加数据'), ('crm_table_delete_view', '可以删除kingadmin中表的数据'))},
        ),
    ]
